In [3]:
from numpy import array
a=array([1,2,3])
print(a)
b=array([1,2,3])
print(b)
c=a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


In [4]:
from numpy.linalg import norm
a=array([1,2,3])
print(a)
l1=norm(a,1)
print(l1)

[1 2 3]
6.0


In [5]:
a=array([1,2,3])
print(a)
l2=norm(a)
print(l2)

[1 2 3]
3.7416573867739413


In [6]:
from math import inf
from numpy import array
from numpy.linalg import norm
a=array([1,2,3])
print(a)
maxnorm=norm(a,inf)
print(maxnorm)

[1 2 3]
3.0


In [7]:
A=array([[1,2],[3,4],[5,6]])
print(A)
b=0.5
print(b)
C=A*b
print(C)

[[1 2]
 [3 4]
 [5 6]]
0.5
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]


In [8]:
from numpy import tril
from numpy import triu
M=array([[1,2,3],[1,2,3],[1,2,3]])
print(M)
lower=tril(M)
print(lower)
upper=triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


In [9]:
#create  diagonal matrix from vector
from numpy import diag
M=array([[1,2,3],[1,2,3],[1,2,3]])
print(M)
d=diag(M)
print(d)
D=diag(d)
print(D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [10]:
from numpy import identity
I=identity(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
#transepose of inverse
from numpy.linalg import inv
Q=array([[1,0],[0,-1]])
print(Q)
V=inv(Q)
print(Q.T)
print(V)
I=Q.dot(Q.T)
print(I)

[[ 1  0]
 [ 0 -1]]
[[ 1  0]
 [ 0 -1]]
[[ 1.  0.]
 [-0. -1.]]
[[1 0]
 [0 1]]


In [12]:
#transepose matrix
from numpy import array
A=array([[1,2],[3,4],[5,6]])
print(A)
C=A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [13]:
#invert matrix
A=array([[1.0,2.0],[3.0,4.0]])
print(A)
B=inv(A)
print(B)
I=A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [14]:
#matrix trace 
#sum of diagonal of matrix
from numpy import trace
A=array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
B=trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [15]:
#matrix determinant
from numpy.linalg import det
A=array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
B=det(A)
print(B)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
-9.51619735392994e-16


In [16]:
#rank matrix
from numpy.linalg import matrix_rank
v1=array([1,2,3])
print(v1)
vr1=matrix_rank(v1)
print(vr1)
v2=array([0,0,0,0,0])
print(v2)
vr2=matrix_rank(v2)
print(vr2)

[1 2 3]
1
[0 0 0 0 0]
0


In [17]:
#create tensor
T=array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]],[[21,22,23],[24,25,26],[27,28,29]]])
print(T.shape)
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [18]:
#addition of two matrix
A=array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]],[[21,22,23],[24,25,26],[27,28,29]]])
B=array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]],[[21,22,23],[24,25,26],[27,28,29]]])
C=A+B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


In [19]:
#multiplicatin of two matrix
A=array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]],[[21,22,23],[24,25,26],[27,28,29]]])
B=array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]],[[21,22,23],[24,25,26],[27,28,29]]])
C=A*B
print(C)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


In [20]:
from numpy import tensordot
A=array([1,2])
B=array([3,4])
C=tensordot(A,B,axes=0)
print(C)

[[3 4]
 [6 8]]


In [21]:
a=array([[1,2],[3,4]])
a.sum(axis=0)

array([4, 6])

In [22]:
#LU decomposition
from scipy.linalg import lu
A=array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
P,L,U=lu(A)
print(P)
print(L)
print(U)
B=P.dot(L).dot(U)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [23]:
from numpy.linalg import qr
A=array([[1,2],[3,4],[5,6]])
print(A)
Q,R=

SyntaxError: invalid syntax (<ipython-input-23-86f2cb0c13f7>, line 4)

In [24]:
from numpy.linalg import eig
A=array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
values,vectors=eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [25]:
from numpy.linalg import eig
A=array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
values,vectors=eig(A)
B=A.dot(vectors[:,0])
print(B)
C=vectors[:,0]*values[0]
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


In [26]:
for i in range(-1,-11,-1):
    print(i)


-1
-2
-3
-4
-5
-6
-7
-8
-9
-10


In [29]:
from numpy import array
A=array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
values,vectors=eig(A)
Q=vectors
R=inv(Q)
L=diag(values)
B=Q.dot()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


TypeError: dot() missing required argument 'b' (pos 1)

In [28]:
from numpy import array
from scipy.linalg import svd
A=array([[1,2],[3,4],[5,6]])
print(A)
U,s,v=svd(A)
print(U)
print(s)
print(v)

[[1 2]
 [3 4]
 [5 6]]
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
